import type { CemeterySize } from '../../settlement/props'
import type { WorldLocationKind } from './worldLocationTypes'

/**
 * Deterministic landmark naming (plan world-012 §2) — a pure function of
 * world seed + location id, so a name is never generated by the UI and
 * never drifts across reloads. Settlements keep their own existing
 * `SettlementDef.name` (plan §2 "Settlementy zachowują istniejący mechanizm
 * nazewnictwa") — this module never names a `settlement` location.
 */

/** djb2-ish string hash, seeded — same "cheap, stable, no external RNG
 *  dependency" contract as `chunkEnvironment.ts`'s `hashChunk`. */
function hashLocationId(seed: number, id: string): number {
  let h = (seed ^ 0x9e3779b9) | 0
  for (let i = 0; i < id.length; i++) {
    h = (Math.imul(h, 31) + id.charCodeAt(i)) | 0
  }
  h = (h ^ (h >>> 13)) * 1274126177
  return (h ^ (h >>> 16)) >>> 0
}

function pick<T>(pool: readonly T[], hash: number): T {
  return pool[hash % pool.length]!
}

const CAVE_ADJECTIVES = [
  'Czarnego Kamienia', 'Zapomniana', 'Głęboka', 'Szeptów', 'Mroczna',
  'Kruczych Skał', 'Zimna', 'Milcząca', 'Wilcza', 'Podziemna',
]
const CAVE_NOUNS = ['Jaskinia', 'Grota', 'Pieczara']

const CEMETERY_ADJECTIVES = [
  'Starych Dębów', 'Zapomnianych', 'Cichych Kamieni', 'Wiecznego Spoczynku',
  'Szarych Krzyży', 'Ostatniej Drogi', 'Starych Wierzb', 'Milczenia',
]
const CEMETERY_NOUNS = ['Cmentarz', 'Kirkut', 'Nekropolia']

const LAKE_ADJECTIVES = [
  'Srebrne', 'Głębokie', 'Spokojne', 'Lazurowe', 'Ciche', 'Turkusowe',
  'Bezdenne', 'Szmaragdowe', 'Zwierciadlane', 'Mgliste',
]
const LAKE_NOUNS = ['Jezioro', 'Staw', 'Toń']

const PEAK_ADJECTIVES = [
  'Miedziany', 'Wichrowy', 'Szary', 'Samotny', 'Ostry', 'Kamienny',
  'Mglisty', 'Żelazny', 'Wysoki', 'Zdradliwy',
]
const PEAK_NOUNS = ['Szczyt', 'Wierchołek', 'Grzbiet']

const POOLS: Record<Exclude<WorldLocationKind, 'settlement'>, {
  adjectives: readonly string[]
  nouns: readonly string[]
}> = {
  cave: { adjectives: CAVE_ADJECTIVES, nouns: CAVE_NOUNS },
  cemetery: { adjectives: CEMETERY_ADJECTIVES, nouns: CEMETERY_NOUNS },
  lake: { adjectives: LAKE_ADJECTIVES, nouns: LAKE_NOUNS },
  mountainPeak: { adjectives: PEAK_ADJECTIVES, nouns: PEAK_NOUNS },
}

/** Larger cemeteries lean toward the more solemn/grand noun pool. */
function cemeteryNoun(hash: number, size: CemeterySize | undefined): string {
  if (size === 'LG') return pick(['Nekropolia', 'Cmentarz'], hash)
  return pick(CEMETERY_NOUNS, hash)
}

export function landmarkName(
  seed: number,
  kind: Exclude<WorldLocationKind, 'settlement'>,
  id: string,
  cemeterySize?: CemeterySize,
): string {
  const hash = hashLocationId(seed, id)
  const pool = POOLS[kind]
  const noun = kind === 'cemetery' ? cemeteryNoun(hash, cemeterySize) : pick(pool.nouns, hash >>> 8)
  const adjective = pick(pool.adjectives, hash >>> 16)
  return `${noun} ${adjective}`
}
