import fs from 'node:fs'
import path from 'node:path'
import { DOCS_DIR } from '../docs/config.js'

const dir = path.resolve('public/models/characters')

function readGlbAnimations(filePath: string): string[] {
  const buffer = fs.readFileSync(filePath)

  if (buffer.toString('ascii', 0, 4) !== 'glTF') {
    throw new Error('Not a GLB file')
  }

  let offset = 12

  while (offset < buffer.length) {
    const chunkLength = buffer.readUInt32LE(offset)
    const chunkType = buffer.readUInt32LE(offset + 4)
    offset += 8

    // JSON chunk: 0x4E4F534A ("JSON")
    if (chunkType === 0x4e4f534a) {
      const json = JSON.parse(
        buffer
          .subarray(offset, offset + chunkLength)
          .toString('utf8')
          .replace(/\0+$/, ''),
      ) as {
        animations?: Array<{ name?: string }>
      }

      return (json.animations ?? []).map(
        (animation, index) => animation.name ?? `<unnamed-${index}>`,
      )
    }

    offset += chunkLength
  }

  return []
}

function listGlbRelPaths(root: string, prefix = ''): string[] {
  const entries = fs.readdirSync(root, { withFileTypes: true })
  const files: string[] = []
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (entry.name === 'parked') continue
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name
    const abs = path.join(root, entry.name)
    if (entry.isDirectory()) {
      files.push(...listGlbRelPaths(abs, rel))
      continue
    }
    if (entry.isFile() && entry.name.toLowerCase().endsWith('.glb')) files.push(rel)
  }
  return files
}

function writeClipTable(
  output: string[],
  files: string[],
  animationModelMatrix: Record<string, string[]>,
): void {
  const totalModels = files.length
  const allModels = files.map((file) => file.replace(/\.glb$/i, ''))

  output.push('| Clip | Stats | Has | Has not |')
  output.push('|------|-------|-----|---------|')

  for (const [animation, models] of Object.entries(animationModelMatrix)) {
    const stats = `${models.length} / ${totalModels}`
    const has = models.join(', ') || '-'
    const hasNot = allModels.filter((model) => !models.includes(model)).join(', ')
    output.push(`| ${animation} | ${stats} | ${has} | ${hasNot} |`)
  }
}

function collectMatrix(files: string[]): Record<string, string[]> {
  const animationModelMatrix: Record<string, string[]> = {}
  for (const file of files) {
    try {
      const animations = readGlbAnimations(path.join(dir, file))
      const model = file.replace(/\.glb$/i, '')
      for (const animation of animations) {
        animationModelMatrix[animation] = [...(animationModelMatrix[animation] ?? []), model]
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      console.error(`\n${file}`)
      console.error(`  ERROR: ${message}`)
    }
  }
  return animationModelMatrix
}

function main() {
  const output: string[] = []
  const allFiles = listGlbRelPaths(dir)
  const rootFiles = allFiles.filter((file) => !file.includes('/'))
  const ubcFiles = allFiles.filter((file) => file.startsWith('ubc/'))

  output.push('# Character Animations')
  output.push('')
  output.push('Generated by `pnpm assets:list-character-animations`. Parked GLBs are skipped.')
  output.push('')

  output.push('## Root models')
  output.push('')
  writeClipTable(output, rootFiles, collectMatrix(rootFiles))
  output.push('')

  output.push('## UBC (`characters/ubc/`)')
  output.push('')
  output.push('Outfit meshes have no clips; locomotion/combat clips live in `ual1_player.glb`.')
  output.push('')
  writeClipTable(output, ubcFiles, collectMatrix(ubcFiles))
  output.push('')

  const outputPath = path.resolve(DOCS_DIR, 'assets/character-animations.md')
  fs.writeFileSync(outputPath, `${output.join('\n')}\n`)
  console.log(`Output written to ${outputPath}`)
}

main()
